# The following lines were added by compinstall


zstyle ':completion:*' menu select
zstyle :compinstall filename '/home/alecsnyder/.zshrc'
autoload -U compinit promptinit zcalc
setopt prompt_subst
compinit
promptinit
autoload -U colors && colors
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
unsetopt beep
setopt autocd correct completealiases HIST_IGNORE_DUPS

bindkey -v
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

function parse_git_branch
{
	ref=$(git symbolic-ref HEAD 2> /dev/null) || return
	echo ${ref#refs/heads/}
}

function gclone {
    cd `gclone-bin $@`
}

function zle-line-init zle-keymap-select {
    NORMAL_CARETS="%{$fg[yellow]%}N>>%{$reset_color%} "
    INSERT_CARETS="%{$fg[yellow]%}I>>%{$reset_color%} "
    STANDARD_CARETS="%{$fg[yellow]%}>>>%{$reset_color%} "
    PROMPT="[%{$fg[red]%}%n%{$reset_color%} in %{$fg[blue]%}%~%{$reset_color%} git %{$fg[green]%}\$(parse_git_branch)%{$reset_color%}]
${${KEYMAP/vicmd/$NORMAL_CARETS}/(main|viins)/$INSERT_CARETS}"
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
export KEYTIMEOUT=1
EDITOR=vim

alias upd='arch_update.sh'
alias pac='sudo pacman -S'
alias pacr='sudo pacman -Rs'
alias start='startup'
alias pacc='sudo pacman -Sc'
alias pacrns="sudo pacman -Rns"
alias grub-update="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias ls='ls --color=auto' 
alias e='emacs '
alias mdisk='udisksctl mount -b'
alias rdisk='udisksctl unmount -b'
alias ldisk='udisks --enumerate'
alias gpush='git push origin master'
alias gpull='git pull origin master'
alias vi='vim'
alias systemctl='sudo systemctl'
alias pacman='sudo pacman'
alias chmox='chmod +x'
alias tmpdir='cd $(mktemp -d)'
date "+%a %h %e %Y %l:%M:%S %p %Z"
. /home/alecsnyder/.nix-profile/etc/profile.d/nix.sh
